""" ENVIRONMENT
set directory=$HOME/.cache/vim/swap
set backupdir=$HOME/.cache/vim/backup
set undodir=$HOME/.cache/vim/undo
set viminfo+=n$HOME/.cache/vim/viminfo

""" GENERAL
set nocompatible
set shell=/bin/bash							" required for GitGutter to work properly
set autoread								" auto update the file when change by another software
set wildmenu								" helper auto complete pop-up for command
set ruler									" show cursor position (line & column number) in the status bar
set number									" show line numbers in the left of the window
set conceallevel=2							" hide special characters in .md files
set laststatus=2							" always show status line
set background=dark							" prevent color scheme changes in tmux
set spell spelllang=en_us,fr
set splitbelow
set splitright
set backup
set undofile
set path=**
" set sessionoptions=curdir,folds
set listchars=eol:↩,tab:→\ ,space:·
set breakindent								" keep tabulation level when wrapping a line
set linebreak								" don't wrap line in the middle of a word
set cursorline								" highlight active line
set mouse=a									" enable mouse support
set noshowmode								" don't show mode in the last line (already in LightLine)
set scrolloff=4								" keep at least 4 visible lines above/below the active line
set termguicolors
set ignorecase								" case insensitive search
set smartcase								" search is case sensitive if a upper case is used
set hlsearch								" Highlight search results
set incsearch								" Show partial match
set lazyredraw								" Don't update screen during macro execution
set tabstop=4								" tab = 4 spaces
set shiftwidth=4							" 1 indentation level = 4 spaces
set shiftround								" round shift value when there is already spaces
set title
set titlestring=vim:\ %t

""" NETRW CONFIG
let g:netrw_banner = 0						" don't show banner on top of file explorer
let g:netrw_liststyle = 3					" enable tree-like view

" " Automatically load and save fold text inside a file
" /!\ Error message when opening non-writable files
" autocmd BufWinLeave *.* mkview 
" autocmd BufWinEnter *.* silent loadview  


source $HOME/.vim/configs/plugins.vim
source $HOME/.vim/configs/keymaps.vim
source $HOME/.vim/configs/theme.vim
source $HOME/.vim/configs/abbreviations.vim
source $HOME/.vim/configs/custom-commands.vim
source $HOME/.vim/configs/custom-functions.vim

augroup reloadConfig
	autocmd!
	autocmd BufWritePost vimrc source <afile>
	autocmd BufWritePost plugins.vim source <afile> | PlugInstall
	autocmd BufWritePost keymaps.vim source <afile>
	autocmd BufWritePost theme.vim source <afile>
	autocmd BufWritePost abbreviations.vim source <afile>
	autocmd BufWritePost custom-commands.vim source <afile>
	autocmd BufWritePost custom-functions.vim source <afile>
augroup end

augroup applyNewExternalConfig
	autocmd!
	autocmd BufWritePost *sxhkdrc !killall sxhkd; setsid sxhkd &
augroup end
